version: 2.1

jobs:
  build:
    working_directory: ~/circleci-ruby
    docker:
      - image: "circleci/ruby:3.2.0"
    steps:
      - checkout
      - run: ruby pair.rb
  test:
    working_directory: ~/circleci-ruby
    docker:
      - image: "circleci/ruby:3.2.0"
    steps:
      - checkout
      - run: rspec spec spec/pair_spec.rb -f d

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build